#!/bin/bash

SANDBOX_RW_BINDS=(~/.omp ~/.cache ~/.local ~/.config/gcloud ~/.npm)
AGENT_CMD="$HOME/dev/oh-my-pi/packages/coding-agent/dist/omp"
HERE="$(realpath .)"
GIT_DIR="$(git rev-parse --git-common-dir 2>/dev/null | xargs -r realpath)"
git_bind=()
[[ -n "$GIT_DIR" ]] && git_bind=(--bind "$GIT_DIR" "$GIT_DIR")
echo "Entering sandbox for $HERE"
bind_args=()
for d in "${SANDBOX_RW_BINDS[@]}"; do bind_args+=(--bind "$d" "$d"); done
bwrap \
	--chdir "$HERE" \
	--ro-bind / / \
	"${bind_args[@]}" \
	"${git_bind[@]}" \
	--dev-bind /dev/null /dev/null \
	--dev-bind /dev/urandom /dev/urandom \
	--tmpfs /tmp \
	--tmpfs /etc/ssh/ssh_config.d \
	--tmpfs /etc/ssh/sshd_config.d \
	--bind "$HERE" "$HERE" \
	--setenv PS1 "sandbox$ " \
	--setenv SEARXNG_ENDPOINT "http://localhost:8888" \
	$AGENT_CMD "$@"
