#!/bin/sh
. $HOME/.zshenv
DISPLAY=:0

sed -i "s/ChangeColors=.*/ChangeColors=false/gI" "$XDG_CONFIG_HOME/okularpartrc"
sed -i "s/set recolor.*/set recolor false/gI" "$XDG_CONFIG_HOME/zathura/zathurarc"

# increase laptop brightness
/usr/bin/brightnessctl s 255

# increase external monitor brightness
$HOME/.local/bin/exmonctl -s 100
