#!/bin/sh

SOUND="/home/phanth/Documents/alarm_tone.mp3"
mpv --no-video --loop=inf $SOUND &> /dev/null &
ACTION=$(dunstify --urgency=critical --action="default,Replay" "$1") 

case "$ACTION" in
    "default") reply_action ;;
    "forwardAction") forward_action ;;
    "2") killall mpv ;;
esac

