#!/bin/sh

database="$PASS_DATABASE"
keyfile="$PASS_KEYFILE"
passgpg="$PASS_PASSFILE"
pass="$(gpg -d "$passgpg" 2> /dev/null)"
timeout=15
entry=$(echo "$pass" | keepassxc-cli ls "$database" -k "$keyfile" 2>/dev/null | menu_cmd)
[ $entry ] || exit

echo "$pass" | keepassxc-cli clip "$database" "$entry" -k "$keyfile" 2> /dev/null
sleep $timeout
echo '' | xclip -sel clip
