#!/bin/sh

lofi_stream_url='https://www.youtube.com/watch?v=5qap5aO4i9A'
adblock_lib="/usr/lib/spotify-adblock.so"
spotify_path="/usr/bin/spotify"
spotify_daemon="xvfb-run -a env LD_PRELOAD=$adblock_lib $spotify_path"
types=$(echo " track \n playlist \n artist \n album \n lofi \n link " | menu_cmd -i -p '' | awk '{ print $2 }')

[ -z "$types" ] && exit 1

[ "$types" = 'lofi' ] && {
	mpv "$lofi_stream_url" &
	exit 0
}

[ "$types" = 'link' ] && {
	mpv "$(xclip -o -selection clipboard)" &
	exit 0
}

query=$(echo '' | menu_cmd -i -p '')

[ -z "$query" ] && exit 1

[ $(playerctl -l | grep -c 'spotify') = 0 ] && {
	$spotify_daemon >/dev/null 2>&1 &

	# wait
	while ! playerctl -l | grep 'spotify'; do
		true
		sleep 2
	done
}

uri=$(
	types="$types" query="$query" python - <<EOF
import spotipy
import os
from spotipy.oauth2 import SpotifyClientCredentials

cid = os.getenv('SPOTIFY_CLIENTID')
csec = os.getenv('SPOTIFY_CLIENTSECRET')
types = os.getenv('types')
query = os.getenv('query')
auth_manager = SpotifyClientCredentials(client_id=cid, client_secret=csec)
sp = spotipy.Spotify(auth_manager=auth_manager)
results = sp.search(q=query, limit=1, type=types)
print(results)
uri = results[types+'s']['items'][0]['uri']
print(uri)
EOF
)

echo "$uri"
playerctl -p spotify open "$uri"
