#!/bin/sh

case "$SESSION" in
sway)
	pkill -f 'bemenu'
	bemenu $* --bottom --fn 'NotoSans Nerd Font Bold 10' -H 23 --tb '#c0caf5' --tf '#1a1b26' --hb '#c0caf5' --hf '#1a1b26'
	;;
labwc)
	pkill -f 'wofi'
	wofi -d -W 35% -H 20% $*
	;;
esac
