#!/bin/sh

choices="  perf \n  perf+ \n  eff \n  eff+ \n🗲 tlp \n ptop"
chosen=$(echo $choices | menu_cmd -i -p '🗲')
[ -z $chosen ] || pkexec util_powerprofile $(echo "$chosen" | awk '{ print $2 }')
