#!/bin/sh

mode=$(echo "  lock
  sleep
  logout
  poweroff
  reboot
" | menu_cmd -i -p '' | awk '{ print $2 }')

[ -z "$mode" ] && exit 1

case "$mode" in
lock) swaylock ;;
sleep) systemctl suspend ;;
logout)
	[ "$SESSION" = "sway" ] && swaymsg exit
	[ "$SESSION" = "labwc" ] && pkill -f labwc
	;;
poweroff) systemctl poweroff ;;
reboot) systemctl reboot ;;
esac
