#!/bin/sh

choices="default\nlinux\nlinux-zen\nlinux-lts\nlinux-harden\nwindow\nvfio"
chosen=$(echo $choices | menu_cmd -i -p '')

case $chosen in
	default) reboot;;
  linux) pkexec grub-reboot 'Advanced options for Arch Linux>Arch Linux, with Linux linux' && reboot;;
	linux-zen) pkexec grub-reboot 'Advanced options for Arch Linux>Arch Linux, with Linux linux-zen' && reboot;;
	linux-lts) pkexec grub-reboot 'Advanced options for Arch Linux>Arch Linux, with Linux linux-lts' && reboot;;
	linux-harden) pkexec grub-reboot 'Advanced options for Arch Linux>Arch Linux, with Linux linux-harden' && reboot;;
  window) pkexec grub-reboot 'Windows 11 - Encrypted Boot' && reboot;;
esac
case $chosen in
