#!/bin/sh

case "$SESSION" in
sway)
	pkill -f 'bemenu'
	bemenu $* --bottom --fn 'NotoSans Nerd Font Bold 10' -H 23 --tb '#ffffff' --tf '#101010' --hb '#ffffff' --hf '#101010'
	;;
labwc)
	pkill -f 'wofi'
	wofi -d -W 35% -H 20% $*
	;;
esac
