#!/bin/sh

database="$PASS_DATABASE"
keyfile="$PASS_KEYFILE"
passgpg="$PASS_PASSFILE"
pass="$(gpg -d "$passgpg" 2>/dev/null)"
[ $pass ] || exit 1
timeout=15
entry=$(echo "$pass" | keepassxc-cli ls "$database" -k "$keyfile" 2>/dev/null | menu_cmd -i -p '')
[ $entry ] || exit 1
echo "$pass" | keepassxc-cli clip "$database" "$entry" -a 'password' -k "$keyfile" 2>/dev/null
sleep $timeout
echo '' | xclip -sel clip
