#!/bin/sh

track=$(echo '' | menu_cmd -i -p ' ')
check() { echo "$(ps aux | grep '/opt/spotify/spotify' | wc -l)"; }
if [  $(check) -le 1 ]; then
  util_spotifydaemon >/dev/null 2>&1 &
fi
while [ $(check) -le 1 ]; do true; done 
util_playtrack "$track"
