#!/bin/sh

choices="$(rclone listremotes)\nphone:\ndatabase"
chosen=$(echo $choices | menu_cmd -i -p "Mount")
mntdir="$HOME/Drives/$chosen"
case $chosen in
	database) pkexec umount /mnt/database ;;
	*) fusermount -u $mntdir ;;
esac

dunstify "Unmount $chosen successfully!"
