#!/bin/sh

choices="$(rclone listremotes)\nphone:\ndatabase"
chosen=$(echo $choices | $MENU_CMD -i -p "Mount")
mntdir="$HOME/Drives/$chosen"
case $chosen in
	database) pkexec mount /mnt/database ;;
	phone:) aft-mtp-mount $HOME/Drives/phone: ;;
  *) 
		rclone mount $chosen $mntdir \
			--dir-cache-time 1000h \
			--poll-interval 5s \
			--umask 007 \
			--cache-dir=$HOME/.cache/rclone \
			--vfs-cache-mode full \
			--vfs-cache-max-size 500G \
			--vfs-cache-max-age 24h \
			--no-checksum \
			--no-modtime \
			--no-seek \
			--transfers 10
					;;
esac

dunstify "Mount $chosen successfully!"
