#!/bin/sh

# menu for starting a timer.

choices="5 min\n15 min\n30 min\n60 min\n120 min\ncustom"
chosen=$(echo $choices | $MENU_CMD -i -p "Timer:")

parseDur(){
	next=$(date -d "$1" +%s)
	now=$(date -d "now" +%s)
	dur=$(expr $next - $now)
	[ $dur -lt 0 ] && exit 1
	return $dur
}

Duration=$(case $chosen in
  ("5 min") echo 300;;
  ("15 min") echo 900;;
  ("30 min") echo 1800;;
  ("60 min") echo 3600;;
  ("120 min") echo 7200;;
  ("custom") 
		echo $(parseDur $(printf '' | $MENU_CMD -i -l 30 -p "Current time: $(date +"%H:%M - A %Y/%m/%d") | Timer duration:"))
esac)

[ -z "$Duration" ] && exit 1

Name=$(printf '' | $MENU_CMD -p 'Name your timer:')

[ -z "$Name" ] && exit 1

if Error=$(sleep $Duration 2>&1); then
    loud-notify "${Duration} seconds finished. Times up !!! ${Name}"
else
    dunstify "$Error" 
fi
