#!/bin/sh
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
interface=$1
command=$2
case $command in 
  managed) 
    ifconfig $interface down
    macchanger -r $interface
    iwconfig $interface mode managed
    ifconfig $interface up
    systemctl restart wpa_supplicant.service
    systemctl restart NetworkManager.service
    iwconfig $interface | grep Mode
    ;;
  monitor)
    rfkill unblock wifi
    systemctl stop NetworkManager.service
    systemctl stop wpa_supplicant.service
    ifconfig $interface down
    macchanger -r $interface
    iwconfig $interface mode monitor
    ifconfig $interface up
    iwconfig $interface | grep Mode
    ;;
  password)
    for file in /etc/NetworkManager/system-connections/*
    do
        filename=$(basename -- "$file")
        filename="${filename%.*}"
        echo "ssid=$filename"
        cat "$file" | grep psk=
        echo " "
    done
    ;;
  *)
    echo "usage: wifictl interface managed|monitor|password"
    ;;
esac
   
    

