#!/usr/bin/python

import spotipy
import os
import argparse
from spotipy.oauth2 import SpotifyClientCredentials

parser = argparse.ArgumentParser(
    description="Retrieve Spotify URI based on query.")
parser.add_argument(
    "-t", "--type", choices=["track", "playlist", "album", "artist"], help="type of query")
parser.add_argument(
    "-q", "--query", help="string used to query the Spotify's API")
args = parser.parse_args()
cid = os.getenv('SPOTIFY_CLIENTID')
csec = os.getenv('SPOTIFY_CLIENTSECRET')
auth_manager = SpotifyClientCredentials(client_id=cid, client_secret=csec)
sp = spotipy.Spotify(auth_manager=auth_manager)
results = sp.search(q=args.query, limit=1, type=args.type)
uri = results[args.type+'s']['items'][0]['uri']
print(uri)
