#!/bin/sh

[ -z $SESSION ] && exit 1

if [ "$SESSION" != "i3" ]; then
	export _JAVA_AWT_WM_NONREPARENTING=1
	export MOZ_DISABLE_RDD_SANDBOX=1
	export MOZ_ENABLE_WAYLAND=1
	export QT_QPA_PLATFORM=wayland
	export CLUTTER_BACKEND=wayland
fi

[ "$SESSION" != "plasma" ] && export QT_QPA_PLATFORMTHEME=qt5ct

echo "Starting $SESSION session..."

case $SESSION in 
	# i3)
	# 	sudo /usr/bin/prime-switch && startx
	# 	;;
	sway)
		XDG_SESSION_TYPE=wayland XDG_CURRENT_DESKTOP=sway sway
		;;
	# gnome)
	# 	XDG_SESSION_TYPE=wayland dbus-run-session gnome-session
	# 	;;
	# plasma)
	# 	XDG_SESSION_TYPE=wayland dbus-run-session startplasma-wayland
	# 	;;
	shell)
		XDG_SESSION_TYPE=shell $SHELL
		;;
	terminal)
		XDG_SESSION_TYPE=terminal XDG_CURRENT_DESKTOP=sway sway -c $XDG_CONFIG_HOME/sway/terminal
		;;
	*)
		echo "Session $SESSION is invalid !"
		;;
esac 
