#!/bin/sh

echo 'winedo:forward X'
xhost +SI:localuser:wine

echo 'winedo:start wine systemd'
sudo loginctl enable-linger wine

XDG_RUNTIME_DIR="/run/user/$(id -u wine)"
DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"
WINE_PREFIX="/home/wine/.wine"

sleep 1

echo 'winedo:starting pipewire'
sudo -u wine env \
  XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
  DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS \
  systemctl --user start pipewire pipewire-pulse

echo 'winedo:running under wine'
sudo -u wine env \
  XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
  DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS \
  WINE_PREFIX=$WINE_PREFIX \
  "$@"

echo 'winedo:stopping pipewire'
sudo -u wine env \
  XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
  DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS \
  systemctl --user stop pipewire pipewire.socket pipewire-pulse pipewire-pulse.socket

echo 'winedo:stop wine systemd'
sudo loginctl disable-linger wine
