#!/bin/sh

dark=false
while getopts 'dl :h' o; do
	case $o in
		d) dark=true ;;
		l) dark=false ;;
		*|h)
			usage
			exit 0 ;;
	esac
done

shift $((OPTIND-1))

if [ "$dark" = true ]; then
	sed -i "s/ChangeColors=.*/ChangeColors=true/gI" "$XDG_CONFIG_HOME/okularpartrc"
	sed -i "s/set recolor.*/set recolor true/gI" "$XDG_CONFIG_HOME/zathura/zathurarc"
else
	sed -i "s/ChangeColors=.*/ChangeColors=false/gI" "$XDG_CONFIG_HOME/okularpartrc"
	sed -i "s/set recolor.*/set recolor false/gI" "$XDG_CONFIG_HOME/zathura/zathurarc"
fi
