#!/bin/sh

echo 'winedo:stopping pipewire'
sudo -u wine \
  XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
  DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS \
  systemctl --user stop pipewire pipewire.socket pipewire-pulse pipewire-pulse.socket

echo 'winedo:stop wine systemd'
sudo loginctl disable-linger wine
