#!/bin/sh

get_state() {
	output=$(swaymsg -t get_inputs -r | jq '.[] | select(.type=="touchpad") | .libinput.send_events')
	state=$([ "$output" = '"enabled"' ] && echo 'enabled' || echo 'disabled')
	echo "$state"
}

while getopts ":tis:" arg; do
	case "$arg" in
	i)
		get_state
		exit 0
		;;
	t)
		new_state=$([ "$(get_state)" = 'enabled' ] && echo 'disabled' || echo 'enabled')
		swaymsg "input type:touchpad events $new_state"
		;;
	s)
		swaymsg "input type:touchpad events ${OPTARG}"
		;;
	esac
done
pkill -SIGUSR1 i3status-rs &
notify-send "Touchpad: $(get_state)" --urgency=low &
