#!/bin/sh

usage() { 
	echo "$0 Usage: [-s value][-i inc_amt][-d dec_amnt]" && grep " .)\ #" $0; exit 0; 
}
[ $# -eq 0 ] && usage
curr_value=$(ddcutil getvcp 10 | awk -F ',' '{ print $1 }' | awk '{ print $9 }')
new_value=$curr_value
get_value=false


while getopts 'gs:i:d: :h' o; do
	case "$o" in
		s) new_value="$OPTARG";;
		i) new_value="$(($curr_value + $OPTARG))" ;;
		d) new_value="$(($curr_value - $OPTARG))" ;;
		g) get_value=true ;;
		h|*)
			usage
			exit 0
			;;
	esac
done


if [ "$get_value" = false ]; then
	ddcutil setvcp 10 $new_value > /dev/null
fi
echo "$new_value"
