#!/bin/sh

file="$1"
case "$1" in
*.cpp | *.c)
	g++ $file -o /tmp/_run && /tmp/_run
	;;
*.rs)
	rustc $file -o /tmp/_run && /tmp/_run
	;;
*.js)
	node $file
	;;
*.ts)
	tsc --target esnext --strict $file --outfile /tmp/_run && node /tmp/_run
	;;
*.py)
	python $file
	;;
*.asm)
	nasm -f elf32 $file -o /tmp/_run.o && ld -m elf_i386 /tmp/_run.o -o /tmp/_run && /tmp/_run
	;;
*.r)
	R $file
	;;
*.m)
	octave $file
	;;
*.scala)
	scala $file
	;;
*.java)
	java $file
	;;
*)
	chmod +x $file &
	>/dev/null && exec $file
	;;
esac
