#!/bin/sh

SWAYSOCK="/run/user/$(id -u $LOGNAME)/sway-ipc.$(id -u $LOGNAME).$(pgrep -x sway).sock"
[ -S "$SWAYSOCK" ] && {
  swaymsg -s $SWAYSOCK input type:keyboard repeat_delay 225
  swaymsg -s $SWAYSOCK input type:keyboard repeat_rate 200
}
