#!/bin/sh

[ ! -d $HOME/.cache/Temp ] && mkdir -p $HOME/.cache/Temp
USERS="$HOME/.local/share/Steam/steamapps/compatdata/userdata/users"
DRIVEC="$HOME/.cache/proton-call/Proton Experimental/pfx/drive_c/"
[ ! -d $HOME/.cache/proton-call ] && {
	mkdir -p "$DRIVEC"
	ln -s "$USERS" "$DRIVEC"
}
WINEESYNC=1 WINEFSYNC=1 gamemoderun mangohud prime-run proton-call -p experimental -r "$@"
