#!/bin/sh

VN="Bamboo"
EN="xkb:us::eng"

while getopts ":ts:" arg; do
	case "$arg" in
	t) [ "$(ibus engine)" = "Bamboo" ] && ibus engine "$EN" || ibus engine "$VN" ;;
	s) [ "${OPTARG}" = "en" ] && ibus engine "$EN" || ibus engine "$VN" ;;
	esac
done
pkill -SIGUSR1 i3status-rs &
notify-send "Ibus: $(ibus engine)" --urgency=low &
