#!/bin/sh

# shared

de_daemons() {
  $HOME/.sh/wm_swhks & # keyboard shortcuts
  foot --server & # terminal server
  ibus-daemon -drxR & # ibus

  # activitywatch
  # aw-watcher-window-wayland &
  # aw-watcher-spotify &
}

wm_daemons() {
  wl-paste --watch cliphist store & # clipboard manager
  $HOME/.sh/menu_overbar & # overbar
  kanshi & # multi monitor manager
  dunst & # notification

  # autobright
  # gammastep -l "${lat}:${lng}" &

  # brightness manager
  location=$(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue")
  lat=$(echo $location | jq '.location | .lat')
  lng=$(echo $location | jq '.location | .lng')
  clight --lat="$lat" --lon="$lng"

  # idle
  swayidle -w \
    timeout 3000 'swaylock -f' \
    timeout 3005 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"' \
    before-sleep 'playerctl pause' \
    before-sleep 'swaylock -f' \
    timeout 6000 '[ "$(cat /sys/class/power_supply/BAT1/status)" = "Discharging" ] && systemctl suspend' &
}

applications() {
  util_browse &
  thunderbird &
  spotify &
  discord &
  keepassxc &
  sleep 1; footclient &
}

case "$SESSION" in
  sway)
    de_daemons &
    wm_daemons &
    applications &
    sworkstyle &
    ;;
  labwc)
    de_daemons &
    wm_daemons &
    applications &
    ;;
  gnome)
    de_daemons &
    ;;
  plasma)
    de_daemons &
    ;;
  shell)
    $HOME/.sh/wm_swhks & # keyboard shortcuts
    ;;
esac &
