#!/bin/sh

ibus-daemon -drxR &
foot --server &
[ "$SESSION" = 'sway' ] || [ "$SESSION" = 'labwc' ] && wl-paste --watch cliphist store &

[ "$SESSION" = 'sway' ] || [ "$SESSION" = 'labwc' ] && $HOME/.sh/menu_overbar &
$HOME/.sh/wm_swhks &
pkexec swhkd -c $HOME/.config/swhkd/swhkdrc -C 150 &

[ "$(cat /sys/class/power_supply/BAT1/status)" = "Discharging" ] && {
  brightnessctl s 0%
  $HOME/.sh/util_exmonctl -s 0
} || {
  brightnessctl s 30%
  $HOME/.sh/util_exmonctl -s 30
} &

# graphical
util_browse &
thunderbird &
spotify &
discord &
keepassxc --keyfiles

sleep 1
footclient &

sleep 5
[ "$SESSION" = 'sway' ] || [ "$SESSION" = 'labwc' ] && gammastep &
aw-watcher-window-wayland &
aw-watcher-spotify &
