#!/bin/sh

ibus-daemon -drxR &
foot --server &
wl-paste --watch cliphist store &

$HOME/.sh/menu_overbar &
$HOME/.sh/wm_swhks &
pkexec swhkd -c $HOME/.config/swhkd/swhkdrc -C 150 &

[ "$(cat /sys/class/power_supply/BAT1/status)" = "Discharging" ] && {
  brightnessctl s 0%
  $HOME/.sh/util_exmonctl -s 0
} || {
  brightnessctl s 50%
  $HOME/.sh/util_exmonctl -s 50
} &

# graphical
util_browse &
thunderbird &
spotify &
discord &

sleep 1
footclient &

sleep 5
gammastep &
aw-watcher-window-wayland &
aw-watcher-spotify &
