#!/bin/sh

$@ &
pid=$!

swaymsg -t subscribe -m '[ "window" ]' \
  | jq --unbuffered --argjson pid "$pid" '.container | select(.pid == $pid) | .id' \
  | xargs -I '@' -- swaymsg '[ con_id=@ ] floating enable' &

subscription=$!

echo '[wm_float.state] Waiting for process to close.'
tail --pid=$pid -f /dev/null
echo '[wm_float.state] Process closed. Kill subscription.'
kill $subscription

  
