#!/bin/sh

sound="/home/phanth/Documents/alarm_tone.mp3"
mpv --no-video --loop=inf $sound &> /dev/null &
action=$(dunstify --urgency=critical --action="default,Replay" "$1") 

case "$action" in
    "default") reply_action ;;
    "forwardAction") forward_action ;;
    "2") killall mpv ;;
esac

