#!/bin/sh

string=
while getopts s: o; do
    case "${o}" in
    s)    string="$OPTARG"
					;;
    esac
done
shift $(($OPTIND - 1))

[ -z "$string" ] && string=$1
cmd="$*"


if [ $SESSION != 'sway' ]; then
  if ! pgrep -x "$cmd"; then
    $cmd &
  else
    dunstify "$cmd is already running!" -t 3000
  fi
  exit 0
fi



con_id=
get_id()
{
  con_id="$(swaymsg -t get_tree | jq '
    first(recurse((.nodes + .floating_nodes)[]) |
    select(any(
    .window_properties.class,
    .window_properties.instance,
    .window_properties.window_role,
    .window_properties.title,
    .name,
		.title,
    .app_id;
    values and match("'"${string}"'"; "i")
    )).id)')"
}

get_id
if [ -n "${con_id:-}" ]; then
  swaymsg "[con_id=${con_id%% }]" focus
else
  $cmd &
  c=0
  while [ -z "${con_id:-}" && $c -le 5 ]; do
    get_id
    sleep 0.5
    c=$(($c+1))
  done
  swaymsg "[con_id=${con_id%% }]" focus
fi
killall wm_open
