#!/bin/sh
hour=$(date +%k | xargs)
minute=$(date +%M)

width=3840
height=$(($width*9/16))

# background="$HOME/Pictures/wallpaper/catalina/$hour.png"
# bgwidth=$(identify $background | awk '{ print $3 }' | awk -F 'x' '{ print $1 }')

scale=$(echo "scale=5;$bgwidth/$width" | bc) 
pi=3.14159265358979323846
angle=$(echo "scale=5;-$pi/2+4*$pi*($hour*60+$minute)/(24*60)" | bc)

# pscircle --output=/tmp/pswall.png \
#   --output-width=$width \
#   --output-height=$height \
#   --background-image=$background \
#   --background-image-scale=$scale \
#   --root-pid=1 \
#   --show-root=1 \
#   --tree-anchor-proc-name='GeckoMain' \
#   --tree-anchor-proc-angle=$pi \
#   --dot-color-min=ffffff77 \
#   --dot-color-max=e81123ff \
#   --dot-border-width=0 \
#   --root-label-angle=$angle \
#   --cpu-max-value=8 \
#   --link-color-min=ffffff33 \
#   --link-color-max=e81123ff \
#   --cpulist-show=0 \
#   --memlist-show=0

[ ! -d /tmp/pswall ] && mkdir /tmp/pswall

pscircle --output=/tmp/pswall/pswall.png \
  --output-width=$width \
  --output-height=$height \
  --background-color='000000' \
  --show-root=1 \
  --tree-anchor-proc-name='systemd' \
  --tree-anchor-proc-angle=$angle \
  --dot-color-min=ffffff \
  --dot-color-max=e81123 \
  --dot-border-width=0 \
  --root-label-angle=$angle \
  --cpu-max-value=8 \
  --link-color-min=ffffff33 \
  --link-color-max=e81123ff \
  --cpulist-show=0 \
  --memlist-show=0 &

# fetch non-frequent data data
[ ! -f /tmp/pswall/weather.png -o ! -f /tmp/pswall/news.png -o ! -f /tmp/pswall/qrcode.png ] && $HOME/.sh/wm_pswall_fetch &

# logo
cat $HOME/.sh/util_logo | textimg \
  -f /usr/share/fonts/nerd-fonts-complete/TTF/Hack\ Bold\ Nerd\ Font\ Complete\ Mono.ttf \
  -b '0,0,0,0' \
  -g cyan \
  -o /tmp/pswall/logo.png

t2im(){
  echo "$1" | textimg \
  -f /usr/share/fonts/nerd-fonts-complete/TTF/Hack\ Bold\ Nerd\ Font\ Complete\ Mono.ttf \
  -b '0,0,0,0' \
  -g '255,255,255,100' \
  -o /tmp/pswall/cmd$2.png
}

# command outputs
# t2im "$(findmnt -o TARGET,SOURCE,FSTYPE)" 1 &
t2im "$(neofetch --stdout --color_blocks off)" 1 &
t2im "$(journalctl --no-pager | tail -n 30)" 2 &
t2im "$(echo "$(task)")" 3 &
t2im "$(lsblk -o NAME,STATE,UUID,FSTYPE,FSAVAIL,FSSIZE,MAJ:MIN,RM,SIZE,RO,TYPE,MOUNTPOINTS)" 4 &
t2im "$(findmnt -o TARGET,SOURCE,FSTYPE)" 5 &
t2im "UPDATE PENDING:\n$($HOME/.sh/util_pendingupdate)" 6 &
t2im "$(netstat --listen -x)" 7 &
# t2im "$(cat $HOME/.sh/util_logo)" 8 &
t2im "$(nmcli d wifi list | head -n 15)" 9 &
wait 

# composite
convert /tmp/pswall/pswall.png \
  -gravity center \( /tmp/pswall/logo.png \) -geometry +0+0 -composite \
  -gravity center \( /tmp/pswall/qrcode.png -resize 125% \) -geometry +0+270 -composite \
  -gravity south \( /tmp/pswall/weather.png \) -geometry -630+520 -composite \
  -gravity southeast \( /tmp/pswall/news.png \) -geometry +10+60 -composite \
  -gravity south \( /tmp/pswall/cmd1.png \) -geometry -520+90 -composite \
  -gravity northwest \( /tmp/pswall/cmd2.png \) -geometry +30+30 -composite \
  -gravity south \( /tmp/pswall/cmd3.png \) -geometry +150+90 -composite \
  -gravity west \( /tmp/pswall/cmd4.png \) -geometry +30+30 -composite \
  -gravity northeast \( /tmp/pswall/cmd5.png \) -geometry +30+30 -composite \
  -gravity southeast \( /tmp/pswall/cmd6.png \) -geometry +900+100 -composite \
  -gravity southwest \( /tmp/pswall/cmd7.png \) -geometry +30+90 -composite \
  -gravity east \( /tmp/pswall/cmd9.png \) -geometry +0+60 -composite \
  -gravity center \
  -pointsize 100 -fill white -annotate +0+5 "$(date +'%H %M')" \
  -pointsize 25 -fill white -annotate +0+100 "$(date +'%a, %b %d')" \
  -pointsize 20 -fill white -annotate +0+100 "$ascii" \
  /tmp/pswall/pswall.png 

  # -gravity center \( /tmp/cmd8.png \) -geometry +0+0 -composite \
  # -gravity north \( /tmp/cmd1.png \) -geometry +0+30 -composite \

# invert
# convert /tmp/pswall.png -channel RGB -negate /tmp/pswall.png


# smooth swaybg switching
pid=$(pidof swaybg)
WAYLAND_DISPLAY=wayland-1 XDG_RUNTIME_DIR="/run/user/$(id -u)" SWAYSOCK="/run/user/$(id -u $LOGNAME)/sway-ipc.$(id -u $LOGNAME).$(pgrep -x sway).sock" swaybg -i '/tmp/pswall/pswall.png' -o '*' -m fill &
sleep 1
kill $pid
