#!/bin/sh

pkill -f 'swaybg'
case "$SESSION" in
sway | labwc)
	# now="$(date +%H)"
	# if [ "$now" -ge 6 -a "$now" -lt 18 ]; then
	# 	swaybg -i "$WALLPAPER_LIGHT" -o '*' -m fill
	# else
	# 	swaybg -i "$WALLPAPER_DARK" -o '*' -m fill
	# fi
	swaybg -i "$WALLPAPER_DARK" -o '*' -m fill
	;;
esac
