#!/bin/sh

if [ "$EUID" = "0" ]; then
  printf "Please run as normal user.\n" >&2
  exit 1
fi

sudo systemctl start libvirtd
systemctl --user start scream-ivshmem-pulse.service
sudo tlp ac && sudo cpupower frequency-set -g performance

# start network default if not already
NET_STATUS=$(virsh net-info default | awk '/Active/ {print $2}')
[ "$NET_STATUS" = "no" ] && virsh net-start default

# start windows 10 vm
virsh start win10

# start looking glass
looking-glass-client -F -k -K 144 spice:input no

# set back mode to powersaving
sudo tlp bat && sudo cpupower frequency-set -g ondemand
sudo systemctl stop libvirtd.service libvirtd.socket libvirtd-ro.socket libvirtd-admin.socket
systemctl --user stop scream-ivshmem-pulse.service
sudo killall dnsmasq

# # Restore keyboard and mouse config
# xset r rate 255 100 &
# xset m mouse 3/2 10 &
# xset s on &
# xset s 600 &
